name: Generate snake animation

on:
  schedule:
    # Thực thi mỗi 12 giờ
    - cron: "*/12 * * * *"
  workflow_dispatch: # Cho phép chạy thủ công từ giao diện GitHub

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      # Bước 1: Tạo file snake.svg
      - name: Generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg?palette=github-dark

      # Bước 2: Đẩy file snake.svg lên nhánh output
      - name: Push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
